'use client'

import '@/styles/globals.scss'
import '@/styles/normalize.css'
import '@/styles/fileupload.scss'
import 'swiper/css'
import 'swiper/css/pagination'

import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import { store } from '@/store'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import '@/services/i18n'
import { appWithTranslation } from 'next-i18next'

const inter = Inter({ subsets: ['latin'] })

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchOnMount: true,
      retryDelay: attemptIndex => Math.min(1000 * 2 ** attemptIndex, 30000),
      retry: 2
    }
  }
})

const MyApp = ({ Component, pageProps }) => {
  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}>
        <Head>
          <title>Tashkent Index</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={inter.className}>
          <Component {...pageProps} />
        </main>
      </QueryClientProvider>
    </Provider>
  )
}

export default MyApp
